### ISSUE TITLE
Build the extension for multiple architectures

### ISSUE THREAD

**Issue by aborroy** [AlfrescoLabs/alfresco-docker-extension#3]
According to the following documentation...

https://docs.docker.com/desktop/extensions-sdk/extensions/multi-arch/

... the Extension may be built for different architectures (mainly amd64 and arm64)

**Comment by ajeetraina** [comment]
Glad that you captured it as part of our recent conversation.
Do let me know once you are done with the implementation.
Can't wait to test it for you. @aborroy

**Comment by aborroy** [comment]
Covered by https://github.com/AlfrescoLabs/alfresco-docker-extension/blob/main/Makefile#L21
