### ISSUE TITLE
Feature Request: Expose ActiveMQ Ports

### ISSUE THREAD

**Issue by coffeemuse** [AlfrescoLabs/alfresco-docker-extension#41]
I have been using the Alfresco Docker Extension as a quick way to spin up a local development instance of Alfresco.  I have just recently started to work with using external events as an Alfresco extension point.  However, the current version of the Alfresco Docker Extension only makes the ActiveMQ web user interface public. 

I'd like to request an enhancement to allow the rest of the ActiveMQ ports be exposed to the Docker host to ease of access for development purposes.

**Comment by aborroy** [comment]
1.3.0 release includes a new option "Expose container ports to your host" to start Alfresco exposing default ports for every service (including also 8161 and 61616 for ActiveMQ)

**Comment by coffeemuse** [comment]
Thank you, @aborroy.  I just updated to 1.3.0 and I have already tested with a my project.  It is working well.
